<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>_01_CL_Achat</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\01_Api_Rest\01_Api_Rest.csproj" />
    <ProjectReference Include="..\01_CL_RegleDeControle\01_CL_RegleDeControle.csproj" />
  </ItemGroup>

</Project>
