CREATE TABLE REALISATIONS(
   id_rea INT UNSIGNED NOT NULL,
   titre_rea VARCHAR(250) NOT NULL,
   date_rea DATE NOT NULL,
   texte_rea TEXT NOT NULL
);

ALTER TABLE realisations
	ADD CONSTRAINT PK_id_rea PRIMARY KEY (id_rea);

ALTER TABLE realisations
	CHANGE COLUMN id_rea id_rea INT UNSIGNED NOT NULL AUTO_INCREMENT;
	
	
CREATE TABLE IMAGES(
   id_img INT UNSIGNED,
   url_img VARCHAR(250) NOT NULL,
   nom_img VARCHAR(100) NOT NULL,
   text_img VARCHAR(300) NOT NULL,
   ext_img VARCHAR(5) NOT NULL
);

ALTER TABLE images
	ADD CONSTRAINT PK_id_img PRIMARY KEY(id_img);
	
ALTER TABLE images
	CHANGE COLUMN id_img id_img INT UNSIGNED NOT NULL AUTO_INCREMENT;
	
ALTER TABLE realisations
	ADD COLUMN id_img INT UNSIGNED; 

ALTER TABLE realisations
	ADD CONSTRAINT FK_id_img FOREIGN KEY(id_img) REFERENCES IMAGES(id_img);	